version: '3.8'
services:
  app:
    build: .
    container_name: url_shortener
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/url_shortener
      - REDIS_URI=redis://redis:6379

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
